/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jliftsim;

import java.util.Properties;
import java.io.File;
import java.io.IOException;
import java.io.FileInputStream;
import org.apache.log4j.Logger;

/**
 *
 * @author BVirtual
 */
public class MainWindow extends javax.swing.JFrame {

    public final String version = "jLiftSim - v0.1 (2012-05-10)";
    private static Logger logger;
    public Properties mainProperties;
    private String mainPath;

    private void updateMainPath() {
        mainPath = getClass().getProtectionDomain().getCodeSource().getLocation().toString().substring(6);
    }

    public String getMainPath() {
        return mainPath;
    }

    public Logger getLogger() {
        return logger;
    }

    public String getLogFileName() {
        return mainProperties.getProperty("LogFileName");
    }

    private void initLogger() {
         logger = MainLogger.getInstance(this.getMainPath() + this.getLogFileName());
         logger.info("logger started");
         logger.info("version: "+this.version);
    }

    private void initProperties() {
        updateMainPath();
        try {
            mainProperties = new java.util.Properties();
            FileInputStream fis = new java.io.FileInputStream(new java.io.File( mainPath + "/myprops.props"));
            mainProperties.load(fis);
            fis.close();

            System.out.println(mainProperties);
        } catch ( IOException ex ) {
            System.err.println( "Error while reading config file." );
            ex.printStackTrace();
        }
    }


    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        initProperties();
        this.setTitle(this.version);
        initLogger();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_inCabinRoomWindow = new javax.swing.JButton();
        jTextField_floorSelect = new javax.swing.JTextField();
        jButton_florrWindow = new javax.swing.JButton();
        jButton_animationWindow = new javax.swing.JButton();
        jButton_engineWindow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Main Window");
        setResizable(false);

        jButton_inCabinRoomWindow.setText("in-cabin room window");

        jButton_florrWindow.setText("floor window");

        jButton_animationWindow.setText("animation window");

        jButton_engineWindow.setText("engine window");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_inCabinRoomWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_floorSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_florrWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton_animationWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_engineWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton_engineWindow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_inCabinRoomWindow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_floorSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_florrWindow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_animationWindow)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_animationWindow;
    private javax.swing.JButton jButton_engineWindow;
    private javax.swing.JButton jButton_florrWindow;
    private javax.swing.JButton jButton_inCabinRoomWindow;
    private javax.swing.JTextField jTextField_floorSelect;
    // End of variables declaration//GEN-END:variables
}
